version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CryptoPools
      MYSQL_USER: diego
      MYSQL_PASSWORD: diego
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6395:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
